app:
  jwt-secret: ${JWT_SECRET}

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL}:5432/efdapi
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASS}
  jpa:
    show-sql: true
  flyway:
    enabled: true
    out-of-order: true